import type { Metadata } from "next";
import { Pacifico } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./_components/Sidebar";
import Footer from "./_components/Footer";



export const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400", 
  variable: "--font-pacifico",

});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      

          <body className={`flex min-h-screen bg-[#f7f6f2] ${pacifico.className} `}>
          <SidebarProvider>
          <AppSidebar />
       <div className="flex flex-col">
       <main className="flex-1  p-6">
       <SidebarTrigger/>

{children}
       </main>
       <Footer/>
       </div>
       </SidebarProvider>

        </body>
    

    </html>
  );
}
